### ISSUE TITLE
uint construct_uint cannot work at version 0.9.x

### ISSUE THREAD

**Issue by cryptoxpotato** [paritytech/parity-common#582]
uint::construct_uint cannot work at version 0.9.x, however it works well on 0.8.x

```
error[E0107]: wrong number of type arguments: expected 1, found 2
  --> programs/src/lib.rs:24:1
   |
24 | / construct_uint! {
25 | |     pub struct U256(4);
26 | | }
   | |_^ unexpected type argument
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```
